#!/bin/bash
echo "Running as $UID"
echo
if [ "$(whoami)" != "root" ]; then
    echo "Must run as root. Exiting"
    exit 2
fi

# Assume trace is active.
IS_ON="$(cat /sys/kernel/tracing/tracing_on)"
function start_trace() {
    if [ $IS_ON -ne 1 ]; then
        echo "Enabling trace"
        echo 1 >/sys/kernel/tracing/tracing_on
        echo
        echo
        sleep 1
    fi
    tail -f /sys/kernel/debug/tracing/trace
}

function cleanup() {
    if [ $IS_ON -ne 1 ]; then
        echo
        echo
        echo "Cleanup: Disabling trace"
        echo 0 >/sys/kernel/tracing/tracing_on
    fi
}

trap cleanup EXIT

start_trace
cleanup
